name: blocsync_server
description: A server for the blocsync package
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  broadcast_bloc: ^0.1.0-dev.2
  dart_frog: ^1.1.0
  dart_frog_web_socket: ^1.0.0
  hive_state_storage:
    path: packages/hive_state_storage
  path: ^1.9.1
  redis_state_storage:
    path: packages/redis_state_storage
  state_storage:
    path: packages/state_storage

dev_dependencies:
  mocktail: ^1.0.3
  test: ^1.25.5
  very_good_analysis: ^5.1.0
