name: blocsync
description: A bloc that syncs its state to the cloud.
version: 0.0.1-dev.2
homepage: https://blocsync.dev
repository: https://github.com/mtwichel/blocsync
issue_tracker: https://github.com/mtwichel/blocsync/issues

environment:
  sdk: ^3.0.0

dependencies:
  bloc: ^9.0.0
  http: ^1.4.0
  hydrated_bloc: ^10.0.0
  meta: ^1.16.0
  web_socket_client: ^0.2.1

dev_dependencies:
  mocktail: ^1.0.4
  test: ^1.25.8
  very_good_analysis: ^6.0.0
