name: synced_bloc
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.7.0

dev_dependencies:
  mocktail: ^1.0.4
  test: ^1.25.8
  very_good_analysis: ^6.0.0
dependencies:
  bloc: ^9.0.0
  hive_ce: ^2.11.3
  http: ^1.4.0
  hydrated_bloc: ^10.0.0
  meta: ^1.16.0
  synchronized: ^3.3.1
  web_socket_client: ^0.2.1
