name: hive_state_storage
description: A state storage using Hive.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  hive_ce: ^2.0.0
  state_storage:
    path: ../state_storage

dev_dependencies:
  mocktail: ^1.0.4
  test: ^1.25.8
  very_good_analysis: ^6.0.0
